name: central_oftalmica_app_cliente
description: Central Oftalmica - Cliente

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  random_string: ^2.1.0
  google_fonts: ^1.1.0
  flutter_modular: ^2.0.1
  flutter_masked_text: ^0.8.0
  dio: ^3.0.9
  intl: ^0.16.1
  rxdart: ^0.24.1
  basic_utils: ^2.7.0-rc.1
  flutter_icons: ^1.1.0
  cached_network_image: ^2.2.0+1
  list_tile_more_customizable: ^1.3.3
  direct_select_flutter: ^1.0.6
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  equatable: ^1.2.3
  barcode_scan: any
  shared_preferences: ^0.5.12+2
  cpfcnpj: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/intro_0.png
    - assets/images/intro_1.png
    - assets/images/intro_2.png
    - assets/images/product.png
    - assets/images/logo_nova.png
    - assets/images/logo_nova_1.png
    - assets/images/logo_alinhada_2.png
    - assets/images/logo-alinhada.png
    - assets/icons/home.png
    - assets/icons/wallet.png
    - assets/icons/info.png
    - assets/icons/heart.png
    - assets/icons/heart_outline.png
    - assets/icons/barcode.png
    - assets/icons/cart.png
    - assets/icons/clip.png
    - assets/icons/email.png
    - assets/icons/security.png
    - assets/icons/open_eye.png
    - assets/icons/requests.png
    - assets/icons/return.png
    - assets/icons/blue_barcode.png
    - assets/icons/drawer.png
    - assets/icons/blue_openbox.png
    - assets/icons/money.png
    - assets/icons/refresh.png
    - assets/icons/bell.png
    - assets/icons/open_box.png
    - assets/icons/drawer_0.png
    - assets/icons/drawer_1.png
    - assets/icons/drawer_2.png
    - assets/icons/drawer_3.png
    - assets/icons/drawer_4.png
    - assets/icons/drawer_5.png
    - assets/icons/drawer_6.png
    - assets/icons/drawer_7.png
    - assets/icons/drawer_8.png
    - assets/icons/drawer_9.png
    - assets/icons/profile_0.png
    - assets/icons/profile_1.png
    - assets/icons/profile_2.png
    - assets/icons/profile_3.png
    - assets/icons/truck.png
    - assets/icons/map_marker.png
    - assets/icons/credit_card.png
    - assets/icons/credito-produto.png
    - assets/icons/credito-financeiro.png
