name: central_oftalmica_app_cliente
description: Central Oftalmica - Cliente

publish_to: "none"

version: 1.0.0+14

environment:
  sdk: ">=2.7.0 <=3.0.0"

dependency_overrides:
  firebase_core_platform_interface: 4.5.1


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  auto_size_text: ^2.1.0
  sizer: ^2.0.13
  cupertino_icons: ^1.0.3
  random_string: ^2.1.0
  google_fonts: ^2.1.0
  flutter_modular: ^3.1.1+1
  flutter_masked_text: ^0.8.0
  dio: ^4.0.0
  intl: ^0.17.0
  rxdart: ^0.27.1
  basic_utils: ^3.1.0
  flutter_icons: ^1.1.0
  cached_network_image: ^3.0.0
  list_tile_more_customizable: 3.0.0
  direct_select_flutter: ^1.0.6
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  equatable: ^2.0.2
  barcode_scan2: ^4.2.1
  shared_preferences: ^2.0.6
  cpfcnpj: ^1.0.3
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/intro_0.png
    - assets/images/intro_1.png
    - assets/images/intro_2.png
    - assets/images/no_image_product.jpeg
    - assets/images/logo_alinhada.png
    - assets/icons/home.png
    - assets/icons/wallet.png
    - assets/icons/info.png
    - assets/icons/heart.png
    - assets/icons/heart_outline.png
    - assets/icons/barcode.png
    - assets/icons/cart.png
    - assets/icons/clip.png
    - assets/icons/email.png
    - assets/icons/security.png
    - assets/icons/open_eye.png
    - assets/icons/requests.png
    - assets/icons/return.png
    - assets/icons/blue_barcode.png
    - assets/icons/drawer.png
    - assets/icons/blue_openbox.png
    - assets/icons/money.png
    - assets/icons/refresh.png
    - assets/icons/bell.png
    - assets/icons/open_box.png
    - assets/icons/drawer_0.png
    - assets/icons/drawer_1.png
    - assets/icons/drawer_2.png
    - assets/icons/drawer_3.png
    - assets/icons/drawer_4.png
    - assets/icons/drawer_5.png
    - assets/icons/drawer_6.png
    - assets/icons/drawer_7.png
    - assets/icons/drawer_8.png
    - assets/icons/drawer_9.png
    - assets/icons/profile_0.png
    - assets/icons/profile_1.png
    - assets/icons/profile_2.png
    - assets/icons/profile_3.png
    - assets/icons/truck.png
    - assets/icons/map_marker.png
    - assets/icons/credit_card.png
    - assets/icons/credito-produto.png
    - assets/icons/credito-financeiro.png
